cmake_minimum_required(VERSION 3.8)
project(camera_detection)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(wuta_msgs REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_python_install_package(${PROJECT_NAME})
install(PROGRAMS scripts/stereo_detection_adapter DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/yolov8_onnx_node DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/yolov8_node DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(stereo_depth test/test_stereo.py)
  ament_add_pytest_test(yolo_decode test/test_yolo.py)
endif()
ament_package()
