<?xml version="1.0"?>
<package format="3">
  <name>camera_detection</name>
  <version>1.0.0</version>
  <description>camera_detection package for WUTA-FSD ROS2 stack</description>
  <maintainer email="wuta@todo.com">WUTA</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>wuta_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
